//@version=4
strategy("BBMA strategy", overlay=true)

/////////////// Time Frame ///////////////
_0 = input(false,  "════════ Test Period ═══════")

testStartYear = input(2017, "Backtest Start Year") 
testStartMonth = input(1, "Backtest Start Month")
testStartDay = input(1, "Backtest Start Day")
testPeriodStart = timestamp(testStartYear,testStartMonth,testStartDay, 0, 0)

testStopYear = input(2019, "Backtest Stop Year")
testStopMonth = input(12, "Backtest Stop Month")
testStopDay = input(31, "Backtest Stop Day")
testPeriodStop = timestamp(testStopYear,testStopMonth,testStopDay, 0, 0)
testPeriod() => time >= testPeriodStart and time <= testPeriodStop ? true : false


_1 = input(false,  "════════ MA═══════")
SOURCE = input(close,title = "MA Source")
lineWidth = input(2,title="Line Width")

_2 = input(false,  "════════ BB ═══════")
BB_SOURCE = input(close, title="BB Source") 
lng = input(20, title="Period")
mut = input(2.0, minval=0.001, maxval=50,title="BB Multiplier")
mut2 = input(2.5, minval=0.001, maxval=50,title="BB2 Multiplier")
mut3 = input(3.0, minval=0.001, maxval=50,title="BB3 Multiplier")
bbl  = input(true,title="Show BB Line")
bbl2 = input(true,title="Show BB2 Line")
bbl3 = input(true,title="Show BB3 Line")
bbLineWidth = input(2,title="BB Line Width")

basis = sma(BB_SOURCE, lng)
dev  = stdev(BB_SOURCE, lng) * mut 
dev2 = stdev(BB_SOURCE, lng) * mut2 
dev3 = stdev(BB_SOURCE, lng) * mut3

upper = basis + dev
lower = basis - dev
upper2 = basis + dev2
lower2 = basis - dev2
upper3 = basis + dev3
lower3 = basis - dev3
sma20  =sma(SOURCE, 20)

plot(bbl?basis:na, color=color.white,linewidth=bbLineWidth,title="BB_Basis")
upperPlot=plot(bbl?upper:na, color=color.white,linewidth=bbLineWidth,title="BB_Upper")
lowerPlot=plot(bbl?lower:na, color=color.white,linewidth=bbLineWidth,title="BB_Lower")

plot(bbl2 ? basis + dev2:na, color=color.white,linewidth=bbLineWidth,title="BB2_Upper")
plot(bbl2 ? basis - dev2:na, color=color.white,linewidth=bbLineWidth,title="BB2_Lower")

plot(bbl3 ? basis + dev3:na, color=color.white,linewidth=bbLineWidth,title="BB3_Upper")
plot(bbl3 ? basis - dev3:na, color=color.white,linewidth=bbLineWidth,title="BB3_Lower")

plot(sma(SOURCE, 10),title="10MA",color=color.yellow,linewidth=lineWidth)
plot(sma20, title="20MA",color=color.red,linewidth=lineWidth)
plot(sma(SOURCE, 55),title="55MA",color=color.purple,linewidth=lineWidth)
plot(sma(SOURCE, 100),title="100MA",color=color.lime,linewidth=lineWidth)
plot(sma(SOURCE, 120),title="120MA",color=color.olive,linewidth=lineWidth)

fill(upperPlot,lowerPlot,color=color.lime)
//plot(sma20, title="20MA",color=color.red,linewidth=lineWidth)
//crossover(sma(close, 14), sma(close, 28))
longCondition =  crossover(close,lower) 
longOutCondition = crossover(close,basis) 

if (testPeriod())
    strategy.entry("Long", strategy.long,when=longCondition) 
    //strategy.exit("exit", "Long", profit = 10, loss = 5)
    //if (longOutCondition)
    strategy.close("Long", when=longOutCondition)  
    
shortCondition =crossunder(close, upper)// crossunder(sma(close, 14), sma(close, 28))
if (testPeriod())
    strategy.entry("Short", strategy.short,when=shortCondition)